import type { Festival } from "./festivals";

export interface FamousPerson {
  id: string;
  nameBn: string;
  nameEn: string;
  birthMD: string;    // "MM-DD" — for recurring annual check
  birthYear: number;
  deathMD?: string;   // "MM-DD" — only for key commemorated dates
  deathYear?: number;
  role: string;
  descBn: string;
  emoji: string;
  wikiUrl: string;
  /** true = birth anniversary already listed in festivals.ts — skip in calendar cell */
  inFestivals?: boolean;
}

export const FAMOUS_PEOPLE: FamousPerson[] = [
  {
    id: "gandhi",
    nameBn: "মহাত্মা গান্ধী",
    nameEn: "Mahatma Gandhi",
    birthMD: "10-02", birthYear: 1869,
    deathMD: "01-30", deathYear: 1948,
    role: "জাতির পিতা",
    descBn: "সত্যাগ্রহ ও অহিংসার পথে ভারতের স্বাধীনতা আন্দোলনের নেতৃত্ব দিয়েছিলেন।",
    emoji: "🕊️",
    wikiUrl: "https://en.wikipedia.org/wiki/Mahatma_Gandhi",
    inFestivals: true,
  },
  {
    id: "bose",
    nameBn: "নেতাজি সুভাষচন্দ্র বসু",
    nameEn: "Subhas Chandra Bose",
    birthMD: "01-23", birthYear: 1897,
    role: "নেতাজি, আজাদ হিন্দ ফৌজের সর্বাধিনায়ক",
    descBn: "\"তোমরা আমাকে রক্ত দাও, আমি তোমাদের স্বাধীনতা দেব\" — এই অমর বাণীর জনক।",
    emoji: "⚔️",
    wikiUrl: "https://en.wikipedia.org/wiki/Subhas_Chandra_Bose",
    inFestivals: true,
  },
  {
    id: "tagore",
    nameBn: "রবীন্দ্রনাথ ঠাকুর",
    nameEn: "Rabindranath Tagore",
    birthMD: "05-07", birthYear: 1861,
    deathYear: 1941,
    role: "বিশ্বকবি",
    descBn: "১৯১৩ সালে সাহিত্যে নোবেল পুরস্কার বিজয়ী। বাংলা সাহিত্যের সর্বশ্রেষ্ঠ কবি।",
    emoji: "✍️",
    wikiUrl: "https://en.wikipedia.org/wiki/Rabindranath_Tagore",
    inFestivals: true,
  },
  {
    id: "vivekananda",
    nameBn: "স্বামী বিবেকানন্দ",
    nameEn: "Swami Vivekananda",
    birthMD: "01-12", birthYear: 1863,
    role: "ধর্মগুরু, যুব আদর্শ",
    descBn: "১৮৯৩ সালে শিকাগো বিশ্বধর্ম সম্মেলনে \"ভ্রাতা ও ভগিনীগণ\" সম্বোধনে বিশ্বকে নাড়া দেন।",
    emoji: "🪷",
    wikiUrl: "https://en.wikipedia.org/wiki/Swami_Vivekananda",
  },
  {
    id: "savitribai",
    nameBn: "সাবিত্রীবাই ফুলে",
    nameEn: "Savitribai Phule",
    birthMD: "01-03", birthYear: 1831,
    role: "ভারতের প্রথম মহিলা শিক্ষিকা",
    descBn: "জ্যোতিরাও ফুলের সঙ্গে মিলে মেয়েদের জন্য ভারতের প্রথম স্কুল প্রতিষ্ঠা করেন।",
    emoji: "📚",
    wikiUrl: "https://en.wikipedia.org/wiki/Savitribai_Phule",
  },
  {
    id: "lala",
    nameBn: "লালা লাজপত রায়",
    nameEn: "Lala Lajpat Rai",
    birthMD: "01-28", birthYear: 1865,
    deathMD: "11-17", deathYear: 1928,
    role: "পাঞ্জাব কেশরি",
    descBn: "সাইমন কমিশনের বিরুদ্ধে শান্তিপূর্ণ মিছিলে ব্রিটিশ লাঠির আঘাতে মৃত্যুবরণ করেন।",
    emoji: "🦁",
    wikiUrl: "https://en.wikipedia.org/wiki/Lala_Lajpat_Rai",
  },
  {
    id: "sarojini",
    nameBn: "সরোজিনী নাইডু",
    nameEn: "Sarojini Naidu",
    birthMD: "02-13", birthYear: 1879,
    role: "ভারতের কোকিল",
    descBn: "ভারতীয় জাতীয় কংগ্রেসের প্রথম মহিলা সভাপতি। কবি ও বাগ্মী হিসেবে বিখ্যাত।",
    emoji: "🌸",
    wikiUrl: "https://en.wikipedia.org/wiki/Sarojini_Naidu",
  },
  {
    id: "bhagat",
    nameBn: "শহীদ ভগৎ সিং",
    nameEn: "Bhagat Singh",
    birthMD: "09-27", birthYear: 1907,
    deathMD: "03-23", deathYear: 1931,
    role: "বিপ্লবী, হিন্দুস্তান সোশ্যালিস্ট রিপাবলিকান অ্যাসোসিয়েশন",
    descBn: "মাত্র ২৩ বছর বয়সে ফাঁসির মঞ্চে \"ইনকিলাব জিন্দাবাদ\" ধ্বনি দিয়ে শহীদ হন।",
    emoji: "🔥",
    wikiUrl: "https://en.wikipedia.org/wiki/Bhagat_Singh",
  },
  {
    id: "ambedkar",
    nameBn: "ড. ভীমরাও আম্বেদকর",
    nameEn: "B. R. Ambedkar",
    birthMD: "04-14", birthYear: 1891,
    role: "সংবিধানের রূপকার",
    descBn: "ভারতের সংবিধান প্রণয়ন কমিটির সভাপতি। দলিত সমাজের অধিকার রক্ষায় আজীবন সংগ্রাম করেন।",
    emoji: "📜",
    wikiUrl: "https://en.wikipedia.org/wiki/B._R._Ambedkar",
  },
  {
    id: "nazrul",
    nameBn: "কাজি নজরুল ইসলাম",
    nameEn: "Kazi Nazrul Islam",
    birthMD: "05-25", birthYear: 1899,
    role: "বিদ্রোহী কবি",
    descBn: "\"বিদ্রোহী\" কবিতা ও \"ধূমকেতু\" পত্রিকার মাধ্যমে ব্রিটিশ শাসনের বিরুদ্ধে কলম চালান।",
    emoji: "🎶",
    wikiUrl: "https://en.wikipedia.org/wiki/Kazi_Nazrul_Islam",
  },
  {
    id: "bismil",
    nameBn: "রাম প্রসাদ বিসমিল",
    nameEn: "Ram Prasad Bismil",
    birthMD: "06-11", birthYear: 1897,
    deathYear: 1927,
    role: "বিপ্লবী কবি",
    descBn: "\"সরফরোশি কি তামান্না\" — এই অমর গজলের রচয়িতা। কাকোরি কাণ্ডে ফাঁসি বরণ করেন।",
    emoji: "🖋️",
    wikiUrl: "https://en.wikipedia.org/wiki/Ram_Prasad_Bismil",
  },
  {
    id: "tilak",
    nameBn: "বাল গঙ্গাধর তিলক",
    nameEn: "Bal Gangadhar Tilak",
    birthMD: "07-23", birthYear: 1856,
    role: "লোকমান্য, স্বরাজের প্রবক্তা",
    descBn: "\"স্বরাজ আমার জন্মগত অধিকার এবং আমি তা নেব\" — এই উক্তির জনক।",
    emoji: "🎯",
    wikiUrl: "https://en.wikipedia.org/wiki/Bal_Gangadhar_Tilak",
  },
  {
    id: "azad",
    nameBn: "চন্দ্রশেখর আজাদ",
    nameEn: "Chandra Shekhar Azad",
    birthMD: "07-23", birthYear: 1906,
    deathMD: "02-27", deathYear: 1931,
    role: "বিপ্লবী",
    descBn: "জীবিত অবস্থায় ব্রিটিশের হাতে ধরা না দেওয়ার শপথ নিয়েছিলেন। আলফ্রেড পার্কে আত্মবলিদান।",
    emoji: "🇮🇳",
    wikiUrl: "https://en.wikipedia.org/wiki/Chandra_Shekhar_Azad",
  },
  {
    id: "mangal-pandey",
    nameBn: "মঙ্গল পাণ্ডে",
    nameEn: "Mangal Pandey",
    birthMD: "07-19", birthYear: 1827,
    deathYear: 1857,
    role: "প্রথম স্বাধীনতা সংগ্রামের অগ্রদূত",
    descBn: "ব্যারাকপুর সেনানিবাসে ব্রিটিশ অফিসারদের বিরুদ্ধে বিদ্রোহ ঘোষণা করেন।",
    emoji: "🫡",
    wikiUrl: "https://en.wikipedia.org/wiki/Mangal_Pandey",
  },
  {
    id: "aurobindo",
    nameBn: "ঋষি অরবিন্দ",
    nameEn: "Sri Aurobindo",
    birthMD: "08-15", birthYear: 1872,
    role: "বিপ্লবী ও দার্শনিক",
    descBn: "প্রথমে সশস্ত্র বিপ্লবের পথিকৃৎ; পরে পন্ডিচেরিতে আশ্রম গড়ে আধ্যাত্মিক সাধনায় মগ্ন হন।",
    emoji: "🧘",
    wikiUrl: "https://en.wikipedia.org/wiki/Sri_Aurobindo",
  },
  {
    id: "bagha-jatin",
    nameBn: "বাঘা যতীন",
    nameEn: "Bagha Jatin",
    birthMD: "12-07", birthYear: 1879,
    deathMD: "09-10", deathYear: 1915,
    role: "যুগান্তর দলের নেতা",
    descBn: "খালি হাতে বাঘ মেরে \"বাঘা যতীন\" নাম পান। বালেশ্বরের যুদ্ধে ব্রিটিশদের বিরুদ্ধে লড়াই করে শহীদ হন।",
    emoji: "🐯",
    wikiUrl: "https://en.wikipedia.org/wiki/Bagha_Jatin",
  },
  {
    id: "khudiram",
    nameBn: "ক্ষুদিরাম বসু",
    nameEn: "Khudiram Bose",
    birthMD: "12-03", birthYear: 1889,
    deathMD: "08-11", deathYear: 1908,
    role: "তরুণতম শহীদ বিপ্লবী",
    descBn: "মাত্র ১৮ বছর বয়সে ফাঁসির মঞ্চে হাসিমুখে মৃত্যুবরণ করেন। বাংলার ঘরে ঘরে বিপ্লবী চেতনা জাগিয়ে দেন।",
    emoji: "🌹",
    wikiUrl: "https://en.wikipedia.org/wiki/Khudiram_Bose",
  },
  {
    id: "bipin",
    nameBn: "বিপিনচন্দ্র পাল",
    nameEn: "Bipin Chandra Pal",
    birthMD: "11-07", birthYear: 1858,
    role: "লাল-বাল-পাল ত্রয়ের অন্যতম",
    descBn: "স্বদেশী, বয়কট ও জাতীয় শিক্ষার পথ দেখান। ভারতের বিপ্লবী চিন্তাধারার পথিকৃৎ।",
    emoji: "📣",
    wikiUrl: "https://en.wikipedia.org/wiki/Bipin_Chandra_Pal",
  },
  {
    id: "nehru",
    nameBn: "জওহরলাল নেহরু",
    nameEn: "Jawaharlal Nehru",
    birthMD: "11-14", birthYear: 1889,
    role: "ভারতের প্রথম প্রধানমন্ত্রী",
    descBn: "আধুনিক ভারতের রূপকার। শিশুদের কাছে \"চাচা নেহরু\"। ১৫ আগস্ট মধ্যরাতে Tryst with Destiny ভাষণ দেন।",
    emoji: "🌹",
    wikiUrl: "https://en.wikipedia.org/wiki/Jawaharlal_Nehru",
  },
  {
    id: "rani-laxmibai",
    nameBn: "রানী লক্ষ্মীবাই",
    nameEn: "Rani Lakshmibai",
    birthMD: "11-19", birthYear: 1828,
    role: "ঝাঁসির রানী",
    descBn: "\"মেরি ঝাঁসি নেহি দুঙ্গি\" — এই ঘোষণা দিয়ে ব্রিটিশদের বিরুদ্ধে যুদ্ধ করেন। অসামান্য সাহসিকতার প্রতীক।",
    emoji: "🗡️",
    wikiUrl: "https://en.wikipedia.org/wiki/Lakshmibai",
  },
  {
    id: "azad-maulana",
    nameBn: "মৌলানা আবুল কালাম আজাদ",
    nameEn: "Maulana Abul Kalam Azad",
    birthMD: "11-11", birthYear: 1888,
    role: "স্বাধীন ভারতের প্রথম শিক্ষামন্ত্রী",
    descBn: "হিন্দু-মুসলিম ঐক্যের প্রবক্তা। ১১ নভেম্বর তাঁর জন্মদিন \"জাতীয় শিক্ষা দিবস\" হিসেবে পালিত।",
    emoji: "📫",
    wikiUrl: "https://en.wikipedia.org/wiki/Maulana_Abul_Kalam_Azad",
  },
  {
    id: "patel",
    nameBn: "সরদার বল্লভভাই প্যাটেল",
    nameEn: "Sardar Vallabhbhai Patel",
    birthMD: "10-31", birthYear: 1875,
    role: "ভারতের লৌহমানব, প্রথম স্বরাষ্ট্রমন্ত্রী",
    descBn: "৫৬২টি দেশীয় রাজ্যকে স্বাধীন ভারতের সঙ্গে যুক্ত করে ভারতের ঐক্য গড়ে তোলেন।",
    emoji: "🏛️",
    wikiUrl: "https://en.wikipedia.org/wiki/Vallabhbhai_Patel",
  },
  {
    id: "shastri",
    nameBn: "লাল বাহাদুর শাস্ত্রী",
    nameEn: "Lal Bahadur Shastri",
    birthMD: "10-02", birthYear: 1904,
    role: "ভারতের দ্বিতীয় প্রধানমন্ত্রী",
    descBn: "\"জয় জওয়ান, জয় কিষান\" স্লোগানের জনক। ১৯৬৫-র ভারত-পাক যুদ্ধে দেশকে নেতৃত্ব দেন।",
    emoji: "🌾",
    wikiUrl: "https://en.wikipedia.org/wiki/Lal_Bahadur_Shastri",
  },
  {
    id: "udham",
    nameBn: "শহীদ উধম সিং",
    nameEn: "Udham Singh",
    birthMD: "12-26", birthYear: 1899,
    role: "জালিয়ানওয়ালাবাগের প্রতিশোধ গ্রহণকারী",
    descBn: "২১ বছর পর লন্ডনে গিয়ে মাইকেল ও'ডায়ারকে গুলি করে জালিয়ানওয়ালাবাগ হত্যাকাণ্ডের প্রতিশোধ নেন।",
    emoji: "🎯",
    wikiUrl: "https://en.wikipedia.org/wiki/Udham_Singh",
  },
  {
    id: "ashfaq",
    nameBn: "আশফাকুল্লা খান",
    nameEn: "Ashfaqulla Khan",
    birthMD: "10-22", birthYear: 1900,
    deathYear: 1927,
    role: "বিপ্লবী, কাকোরি ষড়যন্ত্রে",
    descBn: "রাম প্রসাদ বিসমিলের অন্তরঙ্গ সহযোগী। কাকোরি ট্রেন ডাকাতির মামলায় ফাঁসি।",
    emoji: "🌙",
    wikiUrl: "https://en.wikipedia.org/wiki/Ashfaqulla_Khan",
  },

  // ── Bengal Renaissance · reformers, writers & scientists ────────────────
  {
    id: "rammohan",
    nameBn: "রাজা রামমোহন রায়",
    nameEn: "Raja Ram Mohan Roy",
    birthMD: "05-22", birthYear: 1772,
    deathMD: "09-27", deathYear: 1833,
    role: "সমাজ সংস্কারক, ব্রাহ্মসমাজের প্রতিষ্ঠাতা",
    descBn: "বাংলার নবজাগরণের অগ্রদূত ও আধুনিক ভারতের অন্যতম প্রধান সমাজ সংস্কারক। ১৮২৮ সালে ব্রাহ্মসমাজ প্রতিষ্ঠা করেন এবং তাঁর নিরলস প্রচেষ্টায় ১৮২৯ সালে সতীদাহ প্রথা আইনত নিষিদ্ধ হয়। মুঘল সম্রাট দ্বিতীয় আকবর তাঁকে 'রাজা' উপাধি দেন।",
    emoji: "📜",
    wikiUrl: "https://en.wikipedia.org/wiki/Ram_Mohan_Roy",
  },
  {
    id: "debendranath",
    nameBn: "দেবেন্দ্রনাথ ঠাকুর",
    nameEn: "Debendranath Tagore",
    birthMD: "05-15", birthYear: 1817,
    deathMD: "01-19", deathYear: 1905,
    role: "দার্শনিক, ব্রাহ্ম ধর্মগুরু",
    descBn: "ব্রাহ্ম আন্দোলনের অন্যতম প্রধান নেতা এবং কবি রবীন্দ্রনাথ ঠাকুরের পিতা। তিনি ব্রাহ্মসমাজকে সুসংগঠিত রূপ দেন এবং 'মহর্ষি' নামে পরিচিত হন। শান্তিনিকেতন আশ্রমের প্রতিষ্ঠাতা।",
    emoji: "🪔",
    wikiUrl: "https://en.wikipedia.org/wiki/Debendranath_Tagore",
  },
  {
    id: "keshab",
    nameBn: "কেশবচন্দ্র সেন",
    nameEn: "Keshab Chandra Sen",
    birthMD: "11-19", birthYear: 1838,
    deathMD: "01-08", deathYear: 1884,
    role: "ধর্ম ও সমাজ সংস্কারক",
    descBn: "ব্রাহ্মসমাজের অন্যতম প্রভাবশালী নেতা ও সমাজ সংস্কার আন্দোলনের পুরোধা। নারীশিক্ষা ও বাল্যবিবাহ রোধে তাঁর অবদান উল্লেখযোগ্য।",
    emoji: "🪔",
    wikiUrl: "https://en.wikipedia.org/wiki/Keshab_Chandra_Sen",
  },
  {
    id: "akshay-datta",
    nameBn: "অক্ষয়কুমার দত্ত",
    nameEn: "Akshay Kumar Datta",
    birthMD: "07-15", birthYear: 1820,
    deathMD: "05-28", deathYear: 1886,
    role: "লেখক, যুক্তিবাদী চিন্তক",
    descBn: "বাংলায় যুক্তিবাদী ও বিজ্ঞানমনস্ক চিন্তার অন্যতম পথিকৃৎ। 'তত্ত্ববোধিনী পত্রিকা'র সম্পাদক হিসেবে তিনি জ্ঞানচর্চা ও বিজ্ঞানমনস্কতার প্রসারে গুরুত্বপূর্ণ ভূমিকা রাখেন।",
    emoji: "✍️",
    wikiUrl: "https://en.wikipedia.org/wiki/Akshay_Kumar_Datta",
  },
  {
    id: "dinabandhu",
    nameBn: "দীনবন্ধু মিত্র",
    nameEn: "Dinabandhu Mitra",
    birthMD: "03-31", birthYear: 1830,
    deathMD: "11-01", deathYear: 1873,
    role: "নাট্যকার",
    descBn: "বিখ্যাত নাটক 'নীলদর্পণ'-এর রচয়িতা, যেখানে নীলচাষিদের উপর ব্রিটিশ নীলকরদের অত্যাচারের মর্মস্পর্শী চিত্র ফুটে উঠেছে। তিনি বাংলা নাট্যসাহিত্যের অন্যতম পথিকৃৎ।",
    emoji: "🎭",
    wikiUrl: "https://en.wikipedia.org/wiki/Dinabandhu_Mitra",
  },
  {
    id: "bankim",
    nameBn: "বঙ্কিমচন্দ্র চট্টোপাধ্যায়",
    nameEn: "Bankim Chandra Chattopadhyay",
    birthMD: "06-27", birthYear: 1838,
    deathMD: "04-08", deathYear: 1894,
    role: "ঔপন্যাসিক, সাহিত্যসম্রাট",
    descBn: "বাংলা সাহিত্যের প্রথম প্রধান ঔপন্যাসিক ও 'সাহিত্যসম্রাট'। 'আনন্দমঠ' উপন্যাসে রচিত তাঁর 'বন্দে মাতরম্' সংগীত ভারতের স্বাধীনতা আন্দোলনের মন্ত্র হয়ে ওঠে।",
    emoji: "📖",
    wikiUrl: "https://en.wikipedia.org/wiki/Bankim_Chandra_Chatterjee",
  },
  {
    id: "dwijendralal",
    nameBn: "দ্বিজেন্দ্রলাল রায়",
    nameEn: "Dwijendralal Roy",
    birthMD: "07-19", birthYear: 1863,
    deathMD: "05-17", deathYear: 1913,
    role: "কবি, নাট্যকার, গীতিকার",
    descBn: "দেশাত্মবোধক গান ও ঐতিহাসিক নাটকের জন্য বিখ্যাত। তাঁর রচিত 'ধনধান্যে পুষ্পে ভরা' আজও জনপ্রিয় দেশগান। তাঁর গান 'দ্বিজেন্দ্রগীতি' নামে পরিচিত।",
    emoji: "🎵",
    wikiUrl: "https://en.wikipedia.org/wiki/Dwijendralal_Ray",
  },
  {
    id: "upendrakishore",
    nameBn: "উপেন্দ্রকিশোর রায়চৌধুরী",
    nameEn: "Upendrakishore Ray Chowdhury",
    birthMD: "05-10", birthYear: 1863,
    deathMD: "12-20", deathYear: 1915,
    role: "শিশুসাহিত্যিক, প্রকাশক",
    descBn: "বাংলা শিশুসাহিত্যের পথিকৃৎ ও 'সন্দেশ' পত্রিকার প্রতিষ্ঠাতা। 'টুনটুনির বই' তাঁর অমর সৃষ্টি। তিনি সুকুমার রায়ের পিতা ও সত্যজিৎ রায়ের পিতামহ।",
    emoji: "📚",
    wikiUrl: "https://en.wikipedia.org/wiki/Upendrakishore_Ray_Chowdhury",
  },
  {
    id: "sukumar-ray",
    nameBn: "সুকুমার রায়",
    nameEn: "Sukumar Ray",
    birthMD: "10-30", birthYear: 1887,
    deathMD: "09-10", deathYear: 1923,
    role: "শিশুসাহিত্যিক, ছড়াকার",
    descBn: "বাংলা ননসেন্স সাহিত্যের অপ্রতিদ্বন্দ্বী স্রষ্টা। 'আবোল তাবোল', 'হযবরল' ও 'পাগলা দাশু' তাঁর কালজয়ী রচনা। তিনি চলচ্চিত্রকার সত্যজিৎ রায়ের পিতা।",
    emoji: "✏️",
    wikiUrl: "https://en.wikipedia.org/wiki/Sukumar_Ray",
  },
  {
    id: "ashutosh-mukherjee",
    nameBn: "আশুতোষ মুখোপাধ্যায়",
    nameEn: "Ashutosh Mukherjee",
    birthMD: "06-29", birthYear: 1864,
    deathMD: "05-25", deathYear: 1924,
    role: "শিক্ষাবিদ, বিচারপতি",
    descBn: "কলকাতা বিশ্ববিদ্যালয়ের কিংবদন্তি উপাচার্য, 'বাংলার বাঘ' নামে পরিচিত। উচ্চশিক্ষার প্রসারে তাঁর অবদান অবিস্মরণীয়। তিনি একজন বিশিষ্ট গণিতজ্ঞ ও বিচারপতিও ছিলেন।",
    emoji: "🐯",
    wikiUrl: "https://en.wikipedia.org/wiki/Ashutosh_Mukherjee",
  },
  {
    id: "nivedita",
    nameBn: "ভগিনী নিবেদিতা",
    nameEn: "Sister Nivedita",
    birthMD: "10-28", birthYear: 1867,
    deathMD: "10-13", deathYear: 1911,
    role: "শিক্ষাব্রতী, সমাজসেবী",
    descBn: "স্বামী বিবেকানন্দের শিষ্যা; আইরিশ বংশোদ্ভূত এই মহীয়সী নারী ভারতের সেবায় জীবন উৎসর্গ করেন। নারীশিক্ষা ও স্বাধীনতা আন্দোলনে তাঁর অবদান স্মরণীয়। তাঁর প্রকৃত নাম মার্গারেট এলিজাবেথ নোবেল।",
    emoji: "🕊️",
    wikiUrl: "https://en.wikipedia.org/wiki/Sister_Nivedita",
  },
  {
    id: "atulprasad",
    nameBn: "অতুলপ্রসাদ সেন",
    nameEn: "Atul Prasad Sen",
    birthMD: "10-20", birthYear: 1871,
    deathMD: "08-26", deathYear: 1934,
    role: "গীতিকার, সুরকার",
    descBn: "বিশিষ্ট বাঙালি গীতিকার ও সুরকার, 'অতুলপ্রসাদী' গানের স্রষ্টা। দেশাত্মবোধক ও ভক্তিমূলক গানের জন্য বিখ্যাত। পেশায় তিনি ছিলেন একজন প্রতিষ্ঠিত আইনজীবী।",
    emoji: "🎶",
    wikiUrl: "https://en.wikipedia.org/wiki/Atul_Prasad_Sen",
  },

  // ── Scholars, writers, artists, performers & sportspersons ──────────────
  {
    id: "suniti-chatterji", nameBn: "সুনীতিকুমার চট্টোপাধ্যায়", nameEn: "Suniti Kumar Chatterji",
    birthMD: "11-26", birthYear: 1890, deathMD: "05-29", deathYear: 1977,
    role: "ভাষাবিজ্ঞানী",
    descBn: "ভারতের অন্যতম প্রধান ভাষাবিজ্ঞানী ও পণ্ডিত। বাংলা ভাষার উদ্ভব ও বিকাশ নিয়ে তাঁর গবেষণা যুগান্তকারী।",
    emoji: "🗣️", wikiUrl: "https://en.wikipedia.org/wiki/Suniti_Kumar_Chatterji",
  },
  {
    id: "niharranjan-ray", nameBn: "নীহাররঞ্জন রায়", nameEn: "Nihar Ranjan Ray",
    birthMD: "01-14", birthYear: 1903, deathMD: "08-30", deathYear: 1981,
    role: "ইতিহাসবিদ",
    descBn: "বাঙালির ইতিহাস ও সংস্কৃতি বিষয়ে প্রভাবশালী গবেষক। 'বাঙালীর ইতিহাস' তাঁর বিখ্যাত গ্রন্থ।",
    emoji: "📜", wikiUrl: "https://en.wikipedia.org/wiki/Niharranjan_Ray",
  },
  {
    id: "leela-majumdar", nameBn: "লীলা মজুমদার", nameEn: "Leela Majumdar",
    birthMD: "02-26", birthYear: 1908, deathMD: "04-05", deathYear: 2007,
    role: "শিশুসাহিত্যিক",
    descBn: "বাংলা শিশুসাহিত্যের অন্যতম প্রিয় লেখিকা। 'পদিপিসির বর্মিবাক্স' তাঁর জনপ্রিয় রচনা; রায় পরিবারের সদস্যা।",
    emoji: "📚", wikiUrl: "https://en.wikipedia.org/wiki/Leela_Majumdar",
  },
  {
    id: "shankha-ghosh", nameBn: "শঙ্খ ঘোষ", nameEn: "Shankha Ghosh",
    birthMD: "02-05", birthYear: 1932, deathMD: "04-21", deathYear: 2021,
    role: "কবি",
    descBn: "আধুনিক বাংলার অন্যতম প্রধান কবি ও জ্ঞানপীঠ পুরস্কার বিজয়ী।",
    emoji: "🖋️", wikiUrl: "https://en.wikipedia.org/wiki/Shankha_Ghosh",
  },
  {
    id: "matangini-hazra", nameBn: "মাতঙ্গিনী হাজরা", nameEn: "Matangini Hazra",
    birthMD: "10-19", birthYear: 1870, deathMD: "09-29", deathYear: 1942,
    role: "স্বাধীনতা সংগ্রামী",
    descBn: "ভারত ছাড়ো আন্দোলনের শহিদ। ৭২ বছর বয়সে 'বন্দে মাতরম্' ধ্বনি দিতে দিতে ব্রিটিশ গুলিতে প্রাণ দেন।",
    emoji: "🇮🇳", wikiUrl: "https://en.wikipedia.org/wiki/Matangini_Hazra",
  },
  {
    id: "pritilata", nameBn: "প্রীতিলতা ওয়াদ্দেদার", nameEn: "Pritilata Waddedar",
    birthMD: "05-05", birthYear: 1911, deathMD: "09-24", deathYear: 1932,
    role: "বিপ্লবী",
    descBn: "বাংলার অন্যতম প্রথম নারী বিপ্লবী। সূর্য সেনের নেতৃত্বে ইউরোপীয় ক্লাব আক্রমণে অংশ নিয়ে আত্মাহুতি দেন।",
    emoji: "🔥", wikiUrl: "https://en.wikipedia.org/wiki/Pritilata_Waddedar",
  },
  {
    id: "surya-sen", nameBn: "মাস্টারদা সূর্য সেন", nameEn: "Surya Sen",
    birthMD: "03-22", birthYear: 1894, deathMD: "01-12", deathYear: 1934,
    role: "স্বাধীনতা সংগ্রামী",
    descBn: "চট্টগ্রাম অস্ত্রাগার লুণ্ঠনের নায়ক। 'মাস্টারদা' নামে পরিচিত এই বিপ্লবীকে ব্রিটিশরা ফাঁসি দেয়।",
    emoji: "⚔️", wikiUrl: "https://en.wikipedia.org/wiki/Surya_Sen",
  },
  {
    id: "ashapurna-devi", nameBn: "আশাপূর্ণা দেবী", nameEn: "Ashapurna Devi",
    birthMD: "01-08", birthYear: 1909, deathMD: "07-13", deathYear: 1995,
    role: "সাহিত্যিক",
    descBn: "জ্ঞানপীঠ পুরস্কার বিজয়ী ঔপন্যাসিক। 'প্রথম প্রতিশ্রুতি' তাঁর কালজয়ী উপন্যাস।",
    emoji: "📖", wikiUrl: "https://en.wikipedia.org/wiki/Ashapurna_Devi",
  },
  {
    id: "tarashankar", nameBn: "তারাশঙ্কর বন্দ্যোপাধ্যায়", nameEn: "Tarashankar Bandyopadhyay",
    birthMD: "07-23", birthYear: 1898, deathMD: "09-14", deathYear: 1971,
    role: "সাহিত্যিক",
    descBn: "বিংশ শতাব্দীর অন্যতম শ্রেষ্ঠ বাঙালি ঔপন্যাসিক। 'গণদেবতা', 'হাঁসুলী বাঁকের উপকথা' তাঁর বিখ্যাত রচনা; জ্ঞানপীঠ বিজয়ী।",
    emoji: "📖", wikiUrl: "https://en.wikipedia.org/wiki/Tarasankar_Bandyopadhyay",
  },
  {
    id: "samaresh-basu", nameBn: "সমরেশ বসু", nameEn: "Samaresh Basu",
    birthMD: "12-11", birthYear: 1924, deathMD: "03-12", deathYear: 1988,
    role: "সাহিত্যিক",
    descBn: "জনপ্রিয় বাঙালি ঔপন্যাসিক ও গল্পকার; 'কালকূট' ছদ্মনামেও লিখতেন।",
    emoji: "✍️", wikiUrl: "https://en.wikipedia.org/wiki/Samaresh_Basu",
  },
  {
    id: "narayan-gangopadhyay", nameBn: "নারায়ণ গঙ্গোপাধ্যায়", nameEn: "Narayan Gangopadhyay",
    birthMD: "02-04", birthYear: 1918, deathMD: "11-06", deathYear: 1970,
    role: "সাহিত্যিক",
    descBn: "জনপ্রিয় 'টেনিদা' চরিত্রের স্রষ্টা ও বিশিষ্ট কথাসাহিত্যিক।",
    emoji: "✍️", wikiUrl: "https://en.wikipedia.org/wiki/Narayan_Gangopadhyay",
  },
  {
    id: "hemanta-mukhopadhyay", nameBn: "হেমন্ত মুখোপাধ্যায়", nameEn: "Hemanta Mukhopadhyay",
    birthMD: "06-16", birthYear: 1920, deathMD: "09-26", deathYear: 1989,
    role: "কণ্ঠশিল্পী, সুরকার",
    descBn: "কিংবদন্তি বাংলা ও হিন্দি প্লেব্যাক গায়ক ও সুরকার। রবীন্দ্রসংগীত ও আধুনিক গানে তাঁর কণ্ঠ অমর।",
    emoji: "🎙️", wikiUrl: "https://en.wikipedia.org/wiki/Hemant_Kumar",
  },
  {
    id: "manna-dey", nameBn: "মান্না দে", nameEn: "Manna Dey",
    birthMD: "05-01", birthYear: 1919, deathMD: "10-24", deathYear: 2013,
    role: "কণ্ঠশিল্পী",
    descBn: "ভারতের অন্যতম শ্রেষ্ঠ শাস্ত্রীয়সংগীতনির্ভর প্লেব্যাক গায়ক। 'কফি হাউসের সেই আড্ডা' তাঁর অমর গান।",
    emoji: "🎙️", wikiUrl: "https://en.wikipedia.org/wiki/Manna_Dey",
  },
  {
    id: "sandhya-mukhopadhyay", nameBn: "সন্ধ্যা মুখোপাধ্যায়", nameEn: "Sandhya Mukhopadhyay",
    birthMD: "10-04", birthYear: 1931, deathMD: "02-15", deathYear: 2022,
    role: "কণ্ঠশিল্পী",
    descBn: "প্রবাদপ্রতিম বাংলা প্লেব্যাক গায়িকা, 'গীতশ্রী' নামে পরিচিত।",
    emoji: "🎶", wikiUrl: "https://en.wikipedia.org/wiki/Sandhya_Mukhopadhyay",
  },
  {
    id: "suchitra-sen", nameBn: "সুচিত্রা সেন", nameEn: "Suchitra Sen",
    birthMD: "04-06", birthYear: 1931, deathMD: "01-17", deathYear: 2014,
    role: "অভিনেত্রী",
    descBn: "বাংলা চলচ্চিত্রের অন্যতম শ্রেষ্ঠ মহানায়িকা। উত্তম-সুচিত্রা জুটি বাংলা সিনেমার স্বর্ণযুগের প্রতীক।",
    emoji: "🎬", wikiUrl: "https://en.wikipedia.org/wiki/Suchitra_Sen",
  },
  {
    id: "aparna-sen", nameBn: "অপর্ণা সেন", nameEn: "Aparna Sen",
    birthMD: "10-25", birthYear: 1945,
    role: "অভিনেত্রী, পরিচালক",
    descBn: "প্রশংসিত চলচ্চিত্র পরিচালক ও অভিনেত্রী। '৩৬ চৌরঙ্গি লেন', 'মিস্টার অ্যান্ড মিসেস আইয়ার' তাঁর উল্লেখযোগ্য ছবি।",
    emoji: "🎬", wikiUrl: "https://en.wikipedia.org/wiki/Aparna_Sen",
  },
  {
    id: "soumitra", nameBn: "সৌমিত্র চট্টোপাধ্যায়", nameEn: "Soumitra Chatterjee",
    birthMD: "01-19", birthYear: 1935, deathMD: "11-15", deathYear: 2020,
    role: "অভিনেতা",
    descBn: "সত্যজিৎ রায়ের সঙ্গে যুক্ত কিংবদন্তি অভিনেতা। 'অপুর সংসার' ও 'ফেলুদা' চরিত্রে অবিস্মরণীয়; দাদাসাহেব ফালকে বিজয়ী।",
    emoji: "🎬", wikiUrl: "https://en.wikipedia.org/wiki/Soumitra_Chatterjee",
  },
  {
    id: "sourav-ganguly", nameBn: "সৌরভ গঙ্গোপাধ্যায়", nameEn: "Sourav Ganguly",
    birthMD: "07-08", birthYear: 1972,
    role: "ক্রিকেটার",
    descBn: "ভারতের প্রাক্তন ক্রিকেট অধিনায়ক, 'মহারাজ' ও 'প্রিন্স অফ কলকাতা' নামে পরিচিত।",
    emoji: "🏏", wikiUrl: "https://en.wikipedia.org/wiki/Sourav_Ganguly",
  },
  {
    id: "leander-paes", nameBn: "লিয়েন্ডার পেজ", nameEn: "Leander Paes",
    birthMD: "06-17", birthYear: 1973,
    role: "টেনিস খেলোয়াড়",
    descBn: "ভারতের অন্যতম সফল ডাবলস টেনিস খেলোয়াড় ও অলিম্পিক পদকজয়ী।",
    emoji: "🎾", wikiUrl: "https://en.wikipedia.org/wiki/Leander_Paes",
  },
  {
    id: "amartya-sen", nameBn: "অমর্ত্য সেন", nameEn: "Amartya Sen",
    birthMD: "11-03", birthYear: 1933,
    role: "অর্থনীতিবিদ",
    descBn: "১৯৯৮ সালে অর্থনীতিতে নোবেল পুরস্কার বিজয়ী। কল্যাণ অর্থনীতি ও দারিদ্র্য নিয়ে তাঁর গবেষণা বিশ্বনন্দিত।",
    emoji: "🏅", wikiUrl: "https://en.wikipedia.org/wiki/Amartya_Sen",
  },
  {
    id: "pranab-mukherjee", nameBn: "প্রণব মুখোপাধ্যায়", nameEn: "Pranab Mukherjee",
    birthMD: "12-11", birthYear: 1935, deathMD: "08-31", deathYear: 2020,
    role: "রাষ্ট্রনায়ক",
    descBn: "ভারতের প্রাক্তন রাষ্ট্রপতি ও বিশিষ্ট রাজনীতিবিদ; ভারতরত্ন সম্মানে ভূষিত।",
    emoji: "🏛️", wikiUrl: "https://en.wikipedia.org/wiki/Pranab_Mukherjee",
  },
  {
    id: "bidhan-roy", nameBn: "বিধানচন্দ্র রায়", nameEn: "Bidhan Chandra Roy",
    birthMD: "07-01", birthYear: 1882, deathMD: "07-01", deathYear: 1962,
    role: "চিকিৎসক, রাষ্ট্রনায়ক",
    descBn: "প্রখ্যাত চিকিৎসক ও পশ্চিমবঙ্গের প্রাক্তন মুখ্যমন্ত্রী, 'আধুনিক বাংলার রূপকার'। তাঁর জন্ম ও মৃত্যুদিন ১লা জুলাই ভারতে 'চিকিৎসক দিবস' হিসেবে পালিত হয়।",
    emoji: "🩺", wikiUrl: "https://en.wikipedia.org/wiki/Bidhan_Chandra_Roy",
  },
  {
    id: "atish-dipankar", nameBn: "অতীশ দীপঙ্কর", nameEn: "Atish Dipankar",
    birthMD: "01-01", birthYear: 982, deathMD: "01-01", deathYear: 1054,
    role: "বৌদ্ধ পণ্ডিত",
    descBn: "বাংলার অন্যতম শ্রেষ্ঠ বৌদ্ধ পণ্ডিত, যিনি তিব্বত ও দক্ষিণ-পূর্ব এশিয়ায় বৌদ্ধধর্ম প্রসারে গভীর প্রভাব রাখেন।",
    emoji: "☸️", wikiUrl: "https://en.wikipedia.org/wiki/Atisa",
  },
  {
    id: "sukhalata-rao", nameBn: "সুখলতা রাও", nameEn: "Sukhalata Rao",
    birthMD: "07-26", birthYear: 1886, deathMD: "07-16", deathYear: 1969,
    role: "শিশুসাহিত্যিক",
    descBn: "বাংলা শিশুসাহিত্যের পথিকৃৎ লেখিকা; উপেন্দ্রকিশোর রায়চৌধুরীর কন্যা ও সুকুমার রায়ের ভগিনী।",
    emoji: "📚", wikiUrl: "https://en.wikipedia.org/wiki/Sukhalata_Rao",
  },
  {
    id: "dineshchandra-sen", nameBn: "দীনেশচন্দ্র সেন", nameEn: "Dinesh Chandra Sen",
    birthMD: "11-03", birthYear: 1866, deathMD: "11-20", deathYear: 1939,
    role: "পণ্ডিত, সাহিত্য-ঐতিহাসিক",
    descBn: "বাংলা সাহিত্য ও লোকসংস্কৃতির ইতিহাসকার। 'বঙ্গভাষা ও সাহিত্য' তাঁর উল্লেখযোগ্য গ্রন্থ।",
    emoji: "📜", wikiUrl: "https://en.wikipedia.org/wiki/Dinesh_Chandra_Sen",
  },
  {
    id: "nalinikanta-bhattasali", nameBn: "নলিনীকান্ত ভট্টশালী", nameEn: "Nalinikanta Bhattasali",
    birthMD: "01-24", birthYear: 1888, deathMD: "02-07", deathYear: 1947,
    role: "প্রত্নতত্ত্ববিদ",
    descBn: "বাংলার গুরুত্বপূর্ণ প্রত্নতত্ত্ববিদ ও ইতিহাসবিদ; ঢাকা জাদুঘরের প্রতিষ্ঠাতা কিউরেটর।",
    emoji: "🏺", wikiUrl: "https://en.wikipedia.org/wiki/Nalinikanta_Bhattasali",
  },
  {
    id: "sukumar-sen-cec", nameBn: "সুকুমার সেন", nameEn: "Sukumar Sen",
    birthMD: "01-02", birthYear: 1898, deathMD: "05-13", deathYear: 1963,
    role: "আমলা, প্রথম মুখ্য নির্বাচন কমিশনার",
    descBn: "ভারতের প্রথম মুখ্য নির্বাচন কমিশনার, যিনি ১৯৫১-৫২ সালের প্রথম সাধারণ নির্বাচন পরিচালনা করেন।",
    emoji: "🗳️", wikiUrl: "https://en.wikipedia.org/wiki/Sukumar_Sen_(civil_servant)",
  },
  {
    id: "benoy-sarkar", nameBn: "বিনয়কুমার সরকার", nameEn: "Benoy Kumar Sarkar",
    birthMD: "12-26", birthYear: 1887, deathMD: "11-24", deathYear: 1949,
    role: "অর্থনীতিবিদ, সমাজবিজ্ঞানী",
    descBn: "বিশিষ্ট অর্থনীতিবিদ ও সমাজবিজ্ঞানী।",
    emoji: "📊", wikiUrl: "https://en.wikipedia.org/wiki/Benoy_Kumar_Sarkar",
  },
  {
    id: "naliniranjan-sarkar", nameBn: "নলিনীরঞ্জন সরকার", nameEn: "Nalini Ranjan Sarkar",
    birthMD: "01-12", birthYear: 1882, deathMD: "01-25", deathYear: 1953,
    role: "শিল্পপতি, রাজনীতিবিদ",
    descBn: "বাংলার শিল্পোন্নয়নে গুরুত্বপূর্ণ অবদান রাখা শিল্পপতি ও রাজনীতিবিদ।",
    emoji: "🏭", wikiUrl: "https://en.wikipedia.org/wiki/Nalini_Ranjan_Sarkar",
  },
  {
    id: "nirmalkumar-bose", nameBn: "নির্মলকুমার বসু", nameEn: "Nirmal Kumar Bose",
    birthMD: "01-22", birthYear: 1901, deathMD: "10-15", deathYear: 1972,
    role: "নৃতত্ত্ববিদ",
    descBn: "প্রখ্যাত নৃতত্ত্ববিদ ও মহাত্মা গান্ধীর ঘনিষ্ঠ সহযোগী।",
    emoji: "🧭", wikiUrl: "https://en.wikipedia.org/wiki/Nirmal_Kumar_Bose",
  },
  {
    id: "syama-prasad", nameBn: "শ্যামাপ্রসাদ মুখোপাধ্যায়", nameEn: "Syama Prasad Mukherjee",
    birthMD: "07-06", birthYear: 1901, deathMD: "06-23", deathYear: 1953,
    role: "রাজনীতিবিদ, শিক্ষাবিদ",
    descBn: "ভারতীয় জনসংঘের প্রতিষ্ঠাতা ও প্রাক্তন কেন্দ্রীয় মন্ত্রী; কলকাতা বিশ্ববিদ্যালয়ের কনিষ্ঠতম উপাচার্য।",
    emoji: "🏛️", wikiUrl: "https://en.wikipedia.org/wiki/Syama_Prasad_Mukherjee",
  },
  {
    id: "ashok-mitra", nameBn: "অশোক মিত্র", nameEn: "Ashok Mitra",
    birthMD: "04-10", birthYear: 1928, deathMD: "05-01", deathYear: 2018,
    role: "অর্থনীতিবিদ",
    descBn: "বিশিষ্ট অর্থনীতিবিদ, প্রাবন্ধিক ও পশ্চিমবঙ্গের প্রাক্তন অর্থমন্ত্রী।",
    emoji: "📊", wikiUrl: "https://en.wikipedia.org/wiki/Ashok_Mitra_(economist)",
  },
  {
    id: "shambhu-mitra", nameBn: "শম্ভু মিত্র", nameEn: "Shambhu Mitra",
    birthMD: "08-22", birthYear: 1915, deathMD: "05-19", deathYear: 1997,
    role: "নাট্যব্যক্তিত্ব",
    descBn: "বাংলা থিয়েটারের অন্যতম শ্রেষ্ঠ ব্যক্তিত্ব; 'বহুরূপী' নাট্যদলের প্রতিষ্ঠাতা।",
    emoji: "🎭", wikiUrl: "https://en.wikipedia.org/wiki/Shombhu_Mitra",
  },
  {
    id: "tripti-mitra", nameBn: "তৃপ্তি মিত্র", nameEn: "Tripti Mitra",
    birthMD: "10-25", birthYear: 1925, deathMD: "05-24", deathYear: 1989,
    role: "মঞ্চাভিনেত্রী",
    descBn: "কিংবদন্তি বাংলা মঞ্চাভিনেত্রী।",
    emoji: "🎭", wikiUrl: "https://en.wikipedia.org/wiki/Tripti_Mitra",
  },
  {
    id: "utpal-dutt", nameBn: "উৎপল দত্ত", nameEn: "Utpal Dutt",
    birthMD: "03-29", birthYear: 1929, deathMD: "08-19", deathYear: 1993,
    role: "অভিনেতা, নাট্যকার",
    descBn: "প্রভাবশালী অভিনেতা, নাট্যকার ও রাজনৈতিক থিয়েটারকর্মী; মঞ্চ ও চলচ্চিত্র উভয় ক্ষেত্রেই কিংবদন্তি।",
    emoji: "🎭", wikiUrl: "https://en.wikipedia.org/wiki/Utpal_Dutt",
  },
  {
    id: "badal-sircar", nameBn: "বাদল সরকার", nameEn: "Badal Sircar",
    birthMD: "07-15", birthYear: 1925, deathMD: "05-13", deathYear: 2011,
    role: "নাট্যকার",
    descBn: "'থার্ড থিয়েটার' আন্দোলনের পথিকৃৎ ও বিশিষ্ট নাট্যকার।",
    emoji: "🎭", wikiUrl: "https://en.wikipedia.org/wiki/Badal_Sarkar",
  },
  {
    id: "nandalal-bose", nameBn: "নন্দলাল বসু", nameEn: "Nandalal Bose",
    birthMD: "12-03", birthYear: 1882, deathMD: "04-16", deathYear: 1966,
    role: "চিত্রশিল্পী",
    descBn: "আধুনিক ভারতীয় শিল্পের অন্যতম প্রধান শিল্পী ও শান্তিনিকেতন ধারার রূপকার। ভারতীয় সংবিধানের পাণ্ডুলিপির অলংকরণ তাঁরই কাজ।",
    emoji: "🎨", wikiUrl: "https://en.wikipedia.org/wiki/Nandalal_Bose",
  },
  {
    id: "jamini-roy", nameBn: "যামিনী রায়", nameEn: "Jamini Roy",
    birthMD: "04-11", birthYear: 1887, deathMD: "04-24", deathYear: 1972,
    role: "চিত্রশিল্পী",
    descBn: "ভারতের অন্যতম খ্যাতিমান আধুনিক চিত্রশিল্পী, যিনি বাংলার লোকশিল্পের ধারায় নতুন রীতি গড়ে তোলেন।",
    emoji: "🎨", wikiUrl: "https://en.wikipedia.org/wiki/Jamini_Roy",
  },
  {
    id: "abanindranath", nameBn: "অবনীন্দ্রনাথ ঠাকুর", nameEn: "Abanindranath Tagore",
    birthMD: "08-07", birthYear: 1871, deathMD: "12-05", deathYear: 1951,
    role: "চিত্রশিল্পী",
    descBn: "বেঙ্গল স্কুল অফ আর্টের প্রতিষ্ঠাতা ও আধুনিক ভারতীয় চিত্রকলার পথিকৃৎ। 'ভারতমাতা' তাঁর বিখ্যাত চিত্র।",
    emoji: "🎨", wikiUrl: "https://en.wikipedia.org/wiki/Abanindranath_Tagore",
  },
  {
    id: "gaganendranath", nameBn: "গগনেন্দ্রনাথ ঠাকুর", nameEn: "Gaganendranath Tagore",
    birthMD: "09-18", birthYear: 1867, deathMD: "02-14", deathYear: 1938,
    role: "চিত্রশিল্পী",
    descBn: "আধুনিক ভারতীয় চিত্রকলার পথিকৃৎ ও বাংলার অন্যতম প্রথম কিউবিস্ট শিল্পী।",
    emoji: "🎨", wikiUrl: "https://en.wikipedia.org/wiki/Gaganendranath_Tagore",
  },
  {
    id: "kanika-banerjee", nameBn: "কণিকা বন্দ্যোপাধ্যায়", nameEn: "Kanika Banerjee",
    birthMD: "10-12", birthYear: 1924, deathMD: "04-05", deathYear: 2000,
    role: "রবীন্দ্রসংগীত শিল্পী",
    descBn: "রবীন্দ্রসংগীতের অন্যতম শ্রেষ্ঠ শিল্পী, 'মোহর' নামে পরিচিত।",
    emoji: "🎶", wikiUrl: "https://en.wikipedia.org/wiki/Kanika_Bandopadhyay",
  },
  {
    id: "sukanta", nameBn: "সুকান্ত ভট্টাচার্য", nameEn: "Sukanta Bhattacharya",
    birthMD: "08-15", birthYear: 1926, deathMD: "05-13", deathYear: 1947,
    role: "কবি",
    descBn: "বিদ্রোহী বাঙালি কবি, যাঁর কবিতা তারুণ্য ও সামাজিক ন্যায়ের প্রতীক। মাত্র ২০ বছর বয়সে প্রয়াত হন।",
    emoji: "✊", wikiUrl: "https://en.wikipedia.org/wiki/Sukanta_Bhattacharya",
  },
  {
    id: "buddhadeb-basu", nameBn: "বুদ্ধদেব বসু", nameEn: "Buddhadeb Basu",
    birthMD: "11-30", birthYear: 1908, deathMD: "03-18", deathYear: 1974,
    role: "কবি, সমালোচক",
    descBn: "আধুনিক বাংলা কবিতার অন্যতম প্রধান ব্যক্তিত্ব ও 'কবিতা' পত্রিকার সম্পাদক।",
    emoji: "🖋️", wikiUrl: "https://en.wikipedia.org/wiki/Buddhadeva_Bose",
  },
  {
    id: "annadashankar", nameBn: "অন্নদাশঙ্কর রায়", nameEn: "Annada Shankar Ray",
    birthMD: "03-15", birthYear: 1904, deathMD: "10-28", deathYear: 2002,
    role: "সাহিত্যিক, প্রাবন্ধিক",
    descBn: "বিশিষ্ট প্রাবন্ধিক, কবি ও সাহিত্য সমালোচক; ছড়ার জন্যও বিখ্যাত।",
    emoji: "✍️", wikiUrl: "https://en.wikipedia.org/wiki/Annada_Shankar_Ray",
  },
  {
    id: "premendra-mitra", nameBn: "প্রেমেন্দ্র মিত্র", nameEn: "Premendra Mitra",
    birthMD: "09-04", birthYear: 1904, deathMD: "05-03", deathYear: 1988,
    role: "সাহিত্যিক",
    descBn: "বিখ্যাত 'ঘনাদা' চরিত্রের স্রষ্টা ও বহুমুখী সাহিত্যিক।",
    emoji: "✍️", wikiUrl: "https://en.wikipedia.org/wiki/Premendra_Mitra",
  },
  {
    id: "samaresh-majumdar", nameBn: "সমরেশ মজুমদার", nameEn: "Samaresh Majumdar",
    birthMD: "03-10", birthYear: 1942, deathMD: "05-08", deathYear: 2023,
    role: "ঔপন্যাসিক",
    descBn: "জনপ্রিয় বাঙালি ঔপন্যাসিক, 'অনিমেষ' ত্রয়ী ('উত্তরাধিকার', 'কালবেলা', 'কালপুরুষ')-র জন্য বিখ্যাত।",
    emoji: "📖", wikiUrl: "https://en.wikipedia.org/wiki/Samaresh_Majumdar",
  },
  {
    id: "shirshendu", nameBn: "শীর্ষেন্দু মুখোপাধ্যায়", nameEn: "Shirshendu Mukhopadhyay",
    birthMD: "11-02", birthYear: 1935,
    role: "সাহিত্যিক",
    descBn: "সমকালীন বাংলার অন্যতম প্রিয় সাহিত্যিক; 'মানবজমিন', 'গোঁসাইবাগানের ভূত' তাঁর জনপ্রিয় রচনা।",
    emoji: "📖", wikiUrl: "https://en.wikipedia.org/wiki/Shirshendu_Mukhopadhyay",
  },
  {
    id: "sunil-gangopadhyay", nameBn: "সুনীল গঙ্গোপাধ্যায়", nameEn: "Sunil Gangopadhyay",
    birthMD: "09-07", birthYear: 1934, deathMD: "10-23", deathYear: 2012,
    role: "কবি, ঔপন্যাসিক",
    descBn: "স্বাধীনতা-পরবর্তী বাংলার অন্যতম প্রধান সাহিত্যিক; 'নীললোহিত' ছদ্মনামে পরিচিত। 'সেই সময়', 'প্রথম আলো' তাঁর মহাকাব্যিক উপন্যাস।",
    emoji: "🖋️", wikiUrl: "https://en.wikipedia.org/wiki/Sunil_Gangopadhyay",
  },
  {
    id: "nirendranath", nameBn: "নীরেন্দ্রনাথ চক্রবর্তী", nameEn: "Nirendranath Chakraborty",
    birthMD: "10-19", birthYear: 1924, deathMD: "12-25", deathYear: 2018,
    role: "কবি",
    descBn: "প্রশংসিত বাঙালি কবি ও শিশুসাহিত্যিক; 'আমি কিংবদন্তির কথা বলছি' তাঁর বিখ্যাত কবিতা।",
    emoji: "🖋️", wikiUrl: "https://en.wikipedia.org/wiki/Nirendranath_Chakravarti",
  },
  {
    id: "pc-sorcar", nameBn: "পি. সি. সরকার", nameEn: "P. C. Sorcar",
    birthMD: "02-23", birthYear: 1913, deathMD: "01-06", deathYear: 1971,
    role: "জাদুকর",
    descBn: "বিশ্ববিখ্যাত ভারতীয় জাদুকর, যিনি ভারতীয় জাদুবিদ্যাকে আন্তর্জাতিক মঞ্চে পৌঁছে দেন।",
    emoji: "🎩", wikiUrl: "https://en.wikipedia.org/wiki/P._C._Sorcar",
  },
  {
    id: "bimal-roy", nameBn: "বিমল রায়", nameEn: "Bimal Roy",
    birthMD: "07-12", birthYear: 1909, deathMD: "01-08", deathYear: 1966,
    role: "চলচ্চিত্র পরিচালক",
    descBn: "ভারতের অন্যতম শ্রেষ্ঠ চলচ্চিত্রকার। 'দো বিঘা জমিন', 'মধুমতী' তাঁর কালজয়ী ছবি।",
    emoji: "🎬", wikiUrl: "https://en.wikipedia.org/wiki/Bimal_Roy",
  },
  {
    id: "tapan-sinha", nameBn: "তপন সিংহ", nameEn: "Tapan Sinha",
    birthMD: "10-02", birthYear: 1924, deathMD: "01-15", deathYear: 2009,
    role: "চলচ্চিত্র পরিচালক",
    descBn: "সমাজসচেতন চলচ্চিত্রের জন্য খ্যাত প্রশংসিত বাঙালি পরিচালক; দাদাসাহেব ফালকে বিজয়ী।",
    emoji: "🎬", wikiUrl: "https://en.wikipedia.org/wiki/Tapan_Sinha",
  },
  {
    id: "rituparno", nameBn: "ঋতুপর্ণ ঘোষ", nameEn: "Rituparno Ghosh",
    birthMD: "08-31", birthYear: 1963, deathMD: "05-30", deathYear: 2013,
    role: "চলচ্চিত্র পরিচালক",
    descBn: "সমকালীন বাংলা চলচ্চিত্রের অন্যতম প্রভাবশালী পরিচালক। 'উনিশে এপ্রিল', 'চোখের বালি' তাঁর উল্লেখযোগ্য ছবি।",
    emoji: "🎬", wikiUrl: "https://en.wikipedia.org/wiki/Rituparno_Ghosh",
  },
  {
    id: "suchitra-mitra", nameBn: "সুচিত্রা মিত্র", nameEn: "Suchitra Mitra",
    birthMD: "09-19", birthYear: 1924, deathMD: "01-03", deathYear: 2011,
    role: "রবীন্দ্রসংগীত শিল্পী",
    descBn: "রবীন্দ্রসংগীতের কিংবদন্তি শিল্পী ও শিক্ষাবিদ।",
    emoji: "🎶", wikiUrl: "https://en.wikipedia.org/wiki/Suchitra_Mitra",
  },
  {
    id: "debabrata-biswas", nameBn: "দেবব্রত বিশ্বাস", nameEn: "Debabrata Biswas",
    birthMD: "08-22", birthYear: 1911, deathMD: "08-18", deathYear: 1980,
    role: "রবীন্দ্রসংগীত শিল্পী",
    descBn: "রবীন্দ্রসংগীতের অন্যতম প্রভাবশালী শিল্পী, 'জর্জ বিশ্বাস' নামে পরিচিত।",
    emoji: "🎶", wikiUrl: "https://en.wikipedia.org/wiki/Debabrata_Biswas",
  },
  {
    id: "ali-akbar-khan", nameBn: "আলি আকবর খান", nameEn: "Ali Akbar Khan",
    birthMD: "04-14", birthYear: 1922, deathMD: "06-18", deathYear: 2009,
    role: "সরোদশিল্পী",
    descBn: "বিশ্ববিখ্যাত সরোদশিল্পী ও সংগীতগুরু; মাইহার ঘরানার অন্যতম দিকপাল।",
    emoji: "🎻", wikiUrl: "https://en.wikipedia.org/wiki/Ali_Akbar_Khan",
  },
  {
    id: "chuni-goswami", nameBn: "চুনী গোস্বামী", nameEn: "Chuni Goswami",
    birthMD: "01-15", birthYear: 1938, deathMD: "04-30", deathYear: 2020,
    role: "ফুটবলার",
    descBn: "ভারতের অন্যতম শ্রেষ্ঠ ফুটবলার; ক্রিকেটেও বাংলার হয়ে রঞ্জি ট্রফিতে খেলেছেন।",
    emoji: "⚽", wikiUrl: "https://en.wikipedia.org/wiki/Chuni_Goswami",
  },
  {
    id: "pankaj-roy", nameBn: "পঙ্কজ রায়", nameEn: "Pankaj Roy",
    birthMD: "05-31", birthYear: 1928, deathMD: "02-04", deathYear: 2001,
    role: "ক্রিকেটার",
    descBn: "ভারতের প্রাক্তন ওপেনিং ব্যাটসম্যান ও বাংলার ক্রিকেট-গর্ব।",
    emoji: "🏏", wikiUrl: "https://en.wikipedia.org/wiki/Pankaj_Roy",
  },
  {
    id: "gostha-pal", nameBn: "গোষ্ঠ পাল", nameEn: "Gostha Pal",
    birthMD: "08-20", birthYear: 1896, deathMD: "01-08", deathYear: 1976,
    role: "ফুটবলার",
    descBn: "বাংলার কিংবদন্তি ফুটবল অধিনায়ক, 'চিনের প্রাচীর' নামে খ্যাত।",
    emoji: "⚽", wikiUrl: "https://en.wikipedia.org/wiki/Gostha_Pal",
  },
  {
    id: "anil-gain", nameBn: "অনিল কুমার গাইন", nameEn: "Anil Kumar Gain",
    birthMD: "02-01", birthYear: 1919, deathMD: "02-03", deathYear: 1978,
    role: "গণিতবিদ",
    descBn: "প্রখ্যাত ভারতীয় গণিতবিদ ও পরিসংখ্যানবিদ; গণিত ও পরিসংখ্যান শিক্ষার প্রসারে উল্লেখযোগ্য অবদান।",
    emoji: "🔢", wikiUrl: "https://en.wikipedia.org/wiki/Anil_Kumar_Gain",
  },

  // ── Scientists & cinema icons ───────────────────────────────────────────
  {
    id: "satyajit-ray", nameBn: "সত্যজিৎ রায়", nameEn: "Satyajit Ray",
    birthMD: "05-02", birthYear: 1921, deathMD: "04-23", deathYear: 1992,
    role: "চলচ্চিত্র পরিচালক",
    descBn: "বিশ্বের অন্যতম শ্রেষ্ঠ চলচ্চিত্রকার। 'পথের পাঁচালী', 'অপু ত্রয়ী' ও 'ফেলুদা'-র স্রষ্টা; ১৯৯২ সালে সম্মানসূচক অস্কার ও ভারতরত্ন লাভ করেন।",
    emoji: "🎬", wikiUrl: "https://en.wikipedia.org/wiki/Satyajit_Ray",
  },
  {
    id: "uttam-kumar", nameBn: "উত্তম কুমার", nameEn: "Uttam Kumar",
    birthMD: "09-03", birthYear: 1926, deathMD: "07-24", deathYear: 1980,
    role: "অভিনেতা, মহানায়ক",
    descBn: "বাংলা চলচ্চিত্রের 'মহানায়ক'। উত্তম-সুচিত্রা জুটি বাংলা সিনেমার স্বর্ণযুগের প্রতীক।",
    emoji: "🎬", wikiUrl: "https://en.wikipedia.org/wiki/Uttam_Kumar",
  },
  {
    id: "jagadish-bose", nameBn: "জগদীশচন্দ্র বসু", nameEn: "Jagadish Chandra Bose",
    birthMD: "11-30", birthYear: 1858, deathMD: "11-23", deathYear: 1937,
    role: "বিজ্ঞানী",
    descBn: "বেতার বিজ্ঞান ও উদ্ভিদ-শারীরবৃত্তের পথিকৃৎ। গাছের প্রাণ আছে—এই যুগান্তকারী আবিষ্কার তাঁরই; বসু বিজ্ঞান মন্দিরের প্রতিষ্ঠাতা।",
    emoji: "🔬", wikiUrl: "https://en.wikipedia.org/wiki/Jagadish_Chandra_Bose",
  },
  {
    id: "prafulla-ray", nameBn: "প্রফুল্লচন্দ্র রায়", nameEn: "Prafulla Chandra Ray",
    birthMD: "08-02", birthYear: 1861, deathMD: "06-16", deathYear: 1944,
    role: "রসায়নবিদ",
    descBn: "'ভারতীয় রসায়নের জনক'। বেঙ্গল কেমিক্যালস প্রতিষ্ঠা করে স্বদেশি শিল্পের পথ দেখান।",
    emoji: "⚗️", wikiUrl: "https://en.wikipedia.org/wiki/Prafulla_Chandra_Ray",
  },
  {
    id: "meghnad-saha", nameBn: "মেঘনাদ সাহা", nameEn: "Meghnad Saha",
    birthMD: "10-06", birthYear: 1893, deathMD: "02-16", deathYear: 1956,
    role: "জ্যোতির্পদার্থবিদ",
    descBn: "বিখ্যাত 'সাহা সমীকরণ'-এর প্রণেতা, যা নক্ষত্রের বর্ণালি ব্যাখ্যায় যুগান্তকারী ভূমিকা রাখে।",
    emoji: "🔭", wikiUrl: "https://en.wikipedia.org/wiki/Meghnad_Saha",
  },
  {
    id: "satyendra-bose", nameBn: "সত্যেন্দ্রনাথ বসু", nameEn: "Satyendra Nath Bose",
    birthMD: "01-01", birthYear: 1894, deathMD: "02-04", deathYear: 1974,
    role: "পদার্থবিদ",
    descBn: "যাঁর গবেষণা থেকে 'বোসন' কণা ও বোস-আইনস্টাইন পরিসংখ্যানের জন্ম। আধুনিক পদার্থবিজ্ঞানের অন্যতম দিকপাল।",
    emoji: "⚛️", wikiUrl: "https://en.wikipedia.org/wiki/Satyendra_Nath_Bose",
  },
];

export interface Anniversary extends Omit<Festival, "wikiUrl"> {
  wikiUrl: string;
  person: FamousPerson;
  anniversaryType: "birth" | "death";
  yearsSince: number;
}

export function getAnniversariesForDate(date: Date): Anniversary[] {
  const mm = String(date.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(date.getUTCDate()).padStart(2, "0");
  const md = `${mm}-${dd}`;
  const year = date.getUTCFullYear();

  const results: Anniversary[] = [];

  for (const p of FAMOUS_PEOPLE) {
    if (p.birthMD === md) {
      results.push({
        date: `${year}-${mm}-${dd}`,
        nameBn: `${p.nameBn} জন্মজয়ন্তী`,
        nameEn: `${p.nameEn} Birth Anniversary`,
        category: "national",
        icon: p.emoji,
        wikiUrl: p.wikiUrl,
        person: p,
        anniversaryType: "birth",
        yearsSince: year - p.birthYear,
      });
    }
    if (p.deathMD === md && p.deathYear) {
      results.push({
        date: `${year}-${mm}-${dd}`,
        nameBn: `${p.nameBn} — স্মরণ দিবস`,
        nameEn: `${p.nameEn} Remembrance Day`,
        category: "national",
        icon: "🕯️",
        wikiUrl: p.wikiUrl,
        person: p,
        anniversaryType: "death",
        yearsSince: year - p.deathYear,
      });
    }
  }

  return results;
}
